# Starter pipeline
# Start with a minimal pipeline that you can customize
# to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildDev
    jobs:
      - job: BuildMobileAPP
      - job: BuildReactApp
      - job: BuildNodeApp

  - stage: BuildStaging
    jobs:
      - job: BuildMobileAPP
      - job: BuildReactApp
      - job: BuildNodeApp

  - stage: BuildProd
    jobs:
      - job: BuildMobileAPP
      - job: BuildReactApp
      - job: BuildNodeApp


