# Starter pipeline
# Start with a minimal pipeline that you can customize
# to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildDev
    displayName: Build Stage for dev environment
    jobs:
      - job: BuildMobileAPP
        displayName: Build Mobile App
      - job: BuildReactApp
        displayName: Build React App
      - job: BuildNodeApp
        displayName: Build Node App

  - stage: BuildStaging
    displayName: Build Stage for Staging environment
    jobs:
      - job: BuildMobileAPP
        displayName: Build Mobile App
      - job: BuildReactApp
        displayName: Build Mobile App
      - job: BuildNodeApp
        displayName: Build Mobile App

  - stage: BuildProd
    displayName: Build Stage for Prod environment
    jobs:
      - job: BuildMobileAP
        displayName: Build Mobile App
      - job: BuildReactApp
        displayName: Build Mobile App
      - job: BuildNodeApp
        displayName: Build Mobile App


