trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  # Primera etapa - BuildDev
  - stage: BuildDev
    displayName: Build Stage for dev environment
    jobs:
      - job: BuildMobileApp
        displayName: Build Mobile App
        steps:
          - script: echo building mobile application
            displayName: Building Mobile App
      - job: BuildReactApp
        dependsOn: BuildMobileApp
        displayName: Build React App
        steps:
          - script: echo building react application
            displayName: Building React App
      - job: BuildNodeApp
        dependsOn: BuildReactApp
        displayName: Build Node App
        steps:
          - script: echo building node application
            displayName: Building NodeJS App

  # Segunda etapa - BuildStaging
  - stage: BuildStaging
    dependsOn: BuildDev  # Espera a que el stage BuildDev termine
    displayName: Build Stage for Staging environment
    jobs:
      - job: BuildMobileApp
        displayName: Build Mobile App
        steps:
          - script: echo building mobile application
            displayName: Building Mobile App
      - job: BuildReactApp
        dependsOn: BuildMobileApp
        displayName: Build React App
        steps:
          - script: echo building react application
            displayName: Building React App
      - job: BuildNodeApp
        dependsOn: BuildReactApp
        displayName: Build Node App
        steps:
          - script: echo building node application
            displayName: Building NodeJS App

  # Tercera etapa - BuildProd
  - stage: BuildProd
    dependsOn: BuildStaging  # Espera a que el stage BuildStaging termine
    displayName: Build Stage for Prod environment
    jobs:
      - job: BuildMobileApp
        displayName: Build Mobile App
        steps:
          - script: echo building mobile application
            displayName: Building Mobile App
      - job: BuildReactApp
        dependsOn: BuildMobileApp
        displayName: Build React App
        steps:
          - script: echo building react application
            displayName: Building React App
      - job: BuildNodeApp
        dependsOn: BuildReactApp
        displayName: Build Node App
        steps:
          - script: echo building node application
            displayName: Building NodeJS App
